# Generated by Django 5.1.2 on 2024-11-01 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_hotel_stars"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotel",
            old_name="stars",
            new_name="hotel_stars",
        ),
    ]
