# Generated by Django 5.1.2 on 2024-11-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_rename_stars_hotel_hotel_stars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
