# Generated by Django 5.1.2 on 2024-11-11 01:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_hotel_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="user",
            new_name="user_book",
        ),
    ]
